#!/bin/bash

set -x
if [ ! "$1" == '--ignorestartup' ]; then
    pidof startup.py | xargs kill -TERM
fi
processes=`find ~/rocker -maxdepth 1  -name '*.py' | xargs -n 1 basename | sed 's/\.py//'`
pidof $processes | xargs --no-run-if-empty kill -HUP
killall --signal HUP omxplayer /usr/bin/omxplayer.bin
killall --signal HUP mirage
